# Generated by Django 4.0 on 2021-12-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.URLField(default=''),
        ),
    ]
