# Generated by Django 4.0 on 2021-12-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_date',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('Te', 'Tech'), ('Wo', 'World'), ('CC', 'CryptoCurrency'), ('NC', 'New Science')], default='Te', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
