# Generated by Django 4.0 on 2021-12-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_tags_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('Tech', 'Tech'), ('World', 'World'), ('CryptoCurrency', 'Crypto Currencies'), ('NewScience', 'New Sciences')], default='Te', max_length=32),
        ),
    ]
