# Generated by Django 4.0 on 2021-12-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=32, unique=True)),
                ('value', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
